### ISSUE TITLE
[Feature] Domain 모듈에 banchan  data model class, Repository UseCase 추가 

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#11]
## 📚 To-do

- [x] Domain 모듈에 banchan data model class
- [x] Domain 모듈에 banchan Repository 추가 
- [x] Domain 모듈에 banchan UseCase 추가 

## 🕐 목표 작업 시간

08.09 23:50 - 08.10 01:00
## 📆 실제 작업 시간

08.09 23:50 - 08.10 12:52
