### ISSUE TITLE
[Feature] 장바구니 세부사항 구현

### ISSUE THREAD

**Issue by YM-Byun** [woowa-techcamp-2022/android-banchan-06#111]
## 📚 To-do

- [x] 선택 시 배경 색상 변경
- [x] 최근 본 상품이 없을 때 감추기
- [x] 최근 본 상품 연결
- [x] 수량 텍스트 클릭 시 수량 선택 가능
- [x] 전체적인 에러처리(장바구니 목록이 비어있을때 전체 체크를 누르면 `can't check all` 토스트 뜨는중)
- [x] `empty` 일때 뷰 처리
- [x] 일정 금액 이상이면 배송비 무료 적용
- [x] 우측 상단 선택삭제 텍스트 버튼 ripple 처리
- [x] 주문 버튼 하단에 ${price}이상 담으면 무료배송 금액 처리
- [x] 배경색상 적용, 선택시 흰색처리
