### ISSUE TITLE
[Feature] 주문하기 기능 백그라운드 작업

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#121]
## 📚 To-do

- [x] 주문 시작시 일정 시간 뒤 주문상태 변경
- [x] 주문 상태 완료로 변경 시, Notification 표시
- [x] 주문 상태 변경 시, Header의 Icon 변경
- [x] 주문 상태 변경 시, 주문목록 화면에서 변경 갱신
- [ ] 주문 상태 화면에서, 실시간으로 시간 변경(Optional)
