### ISSUE TITLE
[Refactor] banchan view model 추상화 하여 재사용성 올리기

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#122]
### banchan view model 추상화 하여 재사용성 올리기
Cart 기능들을 추상화 할 수 있을것 같다

## 📚 To-do

- [x] banchan view model 추상화 하여 재사용성 올리기
- [x] Best Banchan 적용
- [x] Main Banchan 적용
- [x] Soup Banchan 적용
- [x] Side Banchan 적용
- [x] Recent Viewed 적용
- [x] Recent Viewed 에 CartItemState 적용이 안되어있던 문제 수정
- [x] 안쓰게 된 코드들 제거

## 🕐 목표 작업 시간

08.23 00:50 - 02:00
## 📆 실제 작업 시간

08.23 00:50 - 02:00
