### ISSUE TITLE
[Refactor] BanchanDao를 CardDao, RecentViewedDao 통합

### ISSUE THREAD

**Issue by YM-Byun** [woowa-techcamp-2022/android-banchan-06#127]
### 이유
- Test code 작성 할 때 CardDao 또는 RecentViewedDao에 대한 테스트를 하려고 할 때에 BanchanDao의 메소드도 같이 테스트 하게 된다. (구조가 이상하게 됨)
- 트랜잭션으로 묶지 않으면 무결성이 보장되지 않는다

## 📚 To-do

- [ ] BanchanDao의 InsertBanchanItem을 RecentViewedDao에도 구현 후 트랜잭션 묶기
- [ ] BanchanDao의 InsertBanchanItem을 CardDao에도 구현 후 트랜잭션 묶기
- [ ] BanchanDao의 RemoveBanchanItem을 CardDao에도 구현 후 트랜잭션 묶기
- [ ] BanchanDao 삭제

## 🕐 목표 작업 시간

미정

## 📆 실제 작업 시간

미정
