### ISSUE TITLE
[Test] Banchan DataSource 테스트 코드 작성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#13]
## 📚 To-do

- [x] Banchan Api Service 테스트 코드 작성
- [x] Banchan DataSource 테스트 코드 작성
- [x] ApiServiceThrowable 적용하여 테스트 코드 수정
- [x] Retrofit Gson 파싱 에러의 경우 테스트 코드 작성

## 🕐 목표 작업 시간

조금씩 학습하여 진행
