### ISSUE TITLE
[Fix] OrderList에서 가격정보가 단일 Item 가격만 표시되는 문제 수정

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#143]
## 📚 To-do

- [x] 배송료 적용
- [x] Item 개수를 가격에 적용
- [x] OrderList 비어있는 경우 대응
- [x] 주문한 item이 single item 인 경우 title에 적용

## 🕐 목표 작업 시간

08.23 15:30 - 16:00
## 📆 실제 작업 시간

08.23 15:30 - 16:00
