### ISSUE TITLE
[Test] Order 데이터 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#157]
## 📚 To-do

- [ ] OrderDao 테스트 코드 작성
- [ ] Order DataSource 테스트 코드 작성
- [ ] Order Repository 테스트 코드 작성
