### ISSUE TITLE
장바구니에서 화면 회전시 crash

### ISSUE THREAD

**Issue by Haemin-Park** [woowa-techcamp-2022/android-banchan-06#184]
## 📚 To-do

- [x] 임시로 장바구니 화면은 세로모드 고정
- [x] updateList를 중단가능한 함수로 설정한뒤, 내부에서 CoroutineScope를 실행하던것을 withContext로 변경
- [x] 다른 Adapter들도 점검

**Comment by wjchoi96** [comment]
그동안 `collectLast`도 사용하고, `suspend` 함수로 설정도 해 보았는데, `event`가 연속으로 들어올때 서로 다른 스레드가 같은 요소에 접근해서 리스트 구성시에 문제가 발생하고 있었다.
코루틴이 중단이 되어야 하는데, 중단이 되지 않고 있던 이유는 `lifeCyclerScope`이 아닌, `Adapter`에서 `CoroutineScope`을 사용하고 있기 때문이였다. 예전에 작성했던 코드라서 신경을 못쓰고 있었던것을 반성했다...
`updateList` 함수를 `suspend`로 설정하고, `CoroutineScope`를 제거한뒤 `withContext`를 사용하도록 변경하였다
