### ISSUE TITLE
[Bug] OrderList, Order화면 수정

### ISSUE THREAD

**Issue by Haemin-Park** [woowa-techcamp-2022/android-banchan-06#193]
### 
총 3개 -> 외 2개로 수정 필요
![image](https://user-images.githubusercontent.com/54823396/186852500-1e927570-4436-4660-806a-64e89a3280b3.png)
![image](https://user-images.githubusercontent.com/54823396/186852523-66d32182-1a3f-4fb6-b031-d5e70b09ce32.png)

## 📚 To-do

- [x] 총 3개 -> 외 2개로 수정 필요
- [x] 가격에 개수가 적용안되어 있는 문제 수정
- [x] 배달 완료 Notification 에도 적용

## 🕐 목표 작업 시간

08.27 18:15 - 18:20
## 📆 실제 작업 시간

08.27 18:15 - 18:20
