### ISSUE TITLE
[Feature] 반찬 주문앱 Api 들의 Entity 생성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#2]
## 📚 To-do

- [x] 기획전 목록 Api Entity 작성
- [x] 메인요리 목록 Api Entity 작성
- [x] 국물요리 목록 Api Entity 작성
- [x] 밑반찬 목록 Api Entity 작성
- [x] 상품 상세 Api Entity 작성

## 🕐 목표 작업 시간

08.09 20:20 - 20:50
## 📆 실제 작업 시간

08.09 20:20 - 20:45
