### ISSUE TITLE
[Feature] Presentation 에러 처리 변경

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#203]
## 📚 To-do

- [x] Throwable을 감지하여, 알맞은 string 리소스를 리턴하는 util 함수 작성 -> 구조상 리소스는 당장 무리여도 상수값을 최대한 활용하도록 설정
- [x] 해당 함수를 사용하여 알맞게 Error View 표시
- [x] ErrorView는 본래 Content 를 가리도록 처리
- [x] Cart Fetch 로직중에 에러가 전달 안되는 문제 수정
- [x] Recent Fetch 로직중에 에러가 전달 안되는 문제 수정

## 🕐 목표 작업 시간

08.26 00:00 - 05:00
## 📆 실제 작업 시간

08.26 00:00 - 05:00
08.27 16:00 - 18:00

**Comment by wjchoi96** [comment]
`CartRepositoryImpl.fetchCartItems()` 에러 처리 변경

- `async`, `await` 를 호출했을때 에러가 발생했다면, `JobCancellationException` 에러가 발생
- `JobCancellationException` 은` try catch` 가 없다면 로그도 찍히지 않고 조용히 처리되는 에러인데다가, 어떤 원인으로 `Cancel` 이 되었는지도 알려주지 않기 때문에, 원인을 알수가 없다
- 우리는 `DataSource` 에서 전달한 에러를 외부로 `throw` 해준 뒤, 외부에서 해당 에러에 따라 처리해줘야 할 작업이 있기때문에 난감한 상황
- 그래서, `async` 내부에서 발생한 에러를 캡쳐해준뒤, `await` 이후 직접 `throw` 해줘서 외부로 에러를 전달해주도록 설정

**Comment by wjchoi96** [comment]
* pagingData.map {} block 내부에서 throw 하게 되면, 어디서도 에러가 집히지 않고 그냥 앱이 터져버린다
     * 내부에서 pagingData.flow.map {} 을 호출하는데, catch 가 따로 등록되어 있지 않아서 그런가..
     * map 내부에서 try catch 로 감싸줘도, 잡았다고 로그가 찍히고 터져버린다..(다시 throw 도 안해줬는데..)
     *
     * pagingData.map{} 은 pagingData 내부 flow 에서 map 을 실시한다.
     * 때문에 해당 flow 를 collect 하기 전까지는 해당 exception 이 발생하지 않을것
     * 해당 flow 를 사용하는 쪽은, PagingDataAdapter 에서 submitData 
     * 내부 코드를 들어가보면 PagingDataDiffer 라는 놈이 collectFrom 를 호출해 collect 를 하는것을 찾아볼 수 있다
     * 근데 여기서 따로 catch 처리는 안해주는듯...
     * UI 쪽에서 에러를 잡을 수 있게 하거나, PageSource 를 재정의 하는 방법으로 진행해야 할듯

**Comment by wjchoi96** [comment]
Room 에서 자체 지원해주는 페이징으로는 PadingData.flow 에서 터지는 문제를 핸들링 할수 없고, 따로 PagingSource를 생성해야 하는데, 이거는 Room에서 지원해주는 지속적인 업데이트가 가능한 현태로 생성하는게 까다로운 상태
하루정도의 시간을 투자해봤지만, 시간관계상 RecentViewed에는 페이징을 제거하고, 기존 로직에 네트워크 체크 로직을 추가하는 방식으로 전환할 예정
