### ISSUE TITLE
[Feature] 장바구니 담기 Bottom Sheet Kotlin Class 작성, 장바구니 추가, 제거 기능 연동

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#22]
## 📚 To-do

- [x] 장바구니 담기 Bottom Sheet Kotlin Class 작성
- [x] 장바구니 담기 Bottom Sheet 연동
- [x] 장바구니에 추가 기능 적용
- [x] 장바구니에서 제거 기능 적용

## 🕐 목표 작업 시간

08.11 10:30 - 11:10
## 📆 실제 작업 시간

08.11 10:30 - 11:30
08.11 13:30 - 14:00
08.11 22:00 - 08.12 01:30
