### ISSUE TITLE
[Test] Cart Data 모듈 테스트 코드 작성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#26]
## 📚 To-do

- [x] Room이 연동된 테스트 코드 작성 방법 학습
- [x] Cart Dao 테스트 코드 작성
- [x] Cart DataSource 테스트 코드 작성
- [x] Cart Repo impl 테스트 코드 작성

## 🕐 목표 작업 시간

08.24 09:30 - 11:30

## 📆 실제 작업 시간

08.24 09:30 - 11:30
08.24 23:30 - 08.25 01:00
