### ISSUE TITLE
[Feature] App Bar 제작

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#49]
## 📚 To-do

- [x] 앱바 xml 파일 제작
- [x] cart icon에 badge 적용
- [x] order icon에 badge 적용

## 🕐 목표 작업 시간

08.14 20:30 - 22:30
08.14 23:30 - 24:00
## 📆 실제 작업 시간

08.14 20:30 - 22:30
08.14 23:30 - 24:00

**Comment by wjchoi96** [comment]
`BadgeUtil` 을 사용해서 `Badge` 처리를 진행하려고 했으나, `number`만 입력가능하고 일정 숫자 이상 `+` 표시는 `maxCharacterCount` 설정을 통한 자리수 단위로만 가능해서 `10+` 처리가 불가능했다.
내부코드를 확인해보니, `maxBadgeNumber` 라는 값이 있어서 해당 값을 어떻게 잘 조절할수만 있다면 `10+` 처리가 가능할 것 같았지만, 관련 설정값이 모두 `private`으로 되어서 직접 제작하는게 아니라면 불가능해보였다

그래서 `menu`의 `app:actionLayout` 속성을 사용하여 `icon`, `badge`를 포함한 `layout` 파일을 직접 설정해서 요구조건에 맞게 설정

**Comment by wjchoi96** [comment]
`Order Icon Badge` 표시는 요구사항을 봤을때, `Badge`를 추가하는게 아닌 이미지를 변경하는게 더 좋아 보여서 그렇게 처리
 - `Badge` 주변으로 투명 `margin` 이 존재하는것으로 보인다
