### ISSUE TITLE
[Feature] Presentation 모듈에 Retrofit Module 작성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#5]
## 📚 To-do

- [x] Presentation 모듈에 retrofit 종속성 추가
- [x] Presentation 모듈에 Hilt 종속성 추가
- [x] Android Application 클래스 생성. Hilt Android App 어노테이션 적용
- [x] App Module 작성
- [x] Retrofit Module 작성

## 🕐 목표 작업 시간

08.09 20:55 - 21:15
## 📆 실제 작업 시간

08.09 20:55 - 21:16
