### ISSUE TITLE
[Feature] 기획전 화면 구현

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#60]
## 📚 To-do

- [x] 기획전 화면 디자인 구현
- [x] 실제 데이터 연동
- [x] ViewPager, Horizontal Recycler View 터치 이벤트 정리

## 🕐 목표 작업 시간

08.16 00:00 - 01:00
## 📆 실제 작업 시간

08.16 00:00 - 01:00
08.16 16:00 - 07:30
08.16 22:30 - 23:30

**Comment by wjchoi96** [comment]
**ViewPager, Horizontal Recycler View 터치 이벤트 정리**

- RecyclerView에 item touch listener을 추가하여, 스크롤 이벤트 조정
- 가로 스크롤중에 리스트의 끝이 아니라면 부모의 스크롤 이벤트를 가로채도록 설정
- 세로 스크롤이라면 부모에게 스크롤 이벤트 전달
