### ISSUE TITLE
[Feature] Presentation 모듈에 Base Activity, Base Fragment 생성

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#7]
## 📚 To-do

- [x] Timber 종속성 추가
- [x] Base Activity 생성
- [x] DefaultLifecycleObserver 추가하여 생명주기에 로그 남기는 기능 추가
- [x] Base Fragment 생성
- [x] Toast, SnackBar Extension Method 추가(Activity, Fragment)

## 🕐 목표 작업 시간

08.09 21:35 - 21:45
## 📆 실제 작업 시간

08.09 21:35 - 21:45
