### ISSUE TITLE
[Feature] UseCase의 결과를 wrapping할 클래스 생성 고민, 적용

### ISSUE THREAD

**Issue by wjchoi96** [woowa-techcamp-2022/android-banchan-06#78]
### UseCase의 결과를 wrapping할 클래스 생성 고민, 적용
현재 List등을 호출할때 에러가 발생한다면 에러가 전달이 되고 있는 상태인데, 이때 Banner, Header 정도의 데이터는 에러가 나도 표시를 해주고 싶다.
하지만 현재 상태에서는 에러와, 데이터를 같이 전달할 수 있는 방법이 생각이 나질않아서, 해당 방법에 대해 고민해보고, 할 수 없다면 UseCase의 결과를 wrapping할 새로운 클래스를 생성하여 적용할 예정 

생성하여 테스트해본결과 좋은것같다

## 📚 To-do

- [x]  UseCase의 결과를 wrapping할 클래스 생성 고민, 적용
- [x] Domain Result 작성
- [x] FetchMainDishUseCase 에 테스트 적용
- [x] throw 날려보면서 결과 테스트
- [ ] Rx, Flow 에 이와같은 형태가 있는지 알아보기

## 🕐 목표 작업 시간

08.17 00:00 - 08:17 13:20
## 📆 실제 작업 시간

08.17 00:00 - 08:17 13:20

- #112 
해당 `Issue`의 변경사항으로 인하여 더 좋은 형태로 발전되었다고 판단해, 해당 `Issue`, `PR`은 `close`처리

**Comment by wjchoi96** [comment]
`inline func` 에 대한 이해도만 있으면, 사용해도 될 것 같다
- https://velog.io/@haero_kim/Kotlin-Inline-Function-%ED%8C%8C%ED%97%A4%EC%B9%98%EA%B8%B0
- 전에 알고 있던 그대로, 람다식이 인자로 전달되는 경우 보통 함수는 해당 람다식을 객체로 만들어 호출하는 방식으로 변환
    - 쓸데없는 객체가 생성되는것 이라고 볼 수 있다
- inline 함수는 람다를 호출하는 부분의 코드가 객체화 되지않고, 그대로 내부코드로 변환이된다
    - 너무 많은 inline 함수의 남발은, 바이트 코드의 양이 많아지는 효과를 가지게 한다
 
**`inline func` 내부에서 `suspend` 함수 호출이 가능한 이유??**
- 추측컨데... suspend 함수를 inline 함수가 아니라면, runCatching 의 block 이 객체가 되어서, 해당 객체가 호출되는 방식이 될텐데
그렇다면 suspend 함수 내부에서 호출되는 형태가 아니라서 에러가 발생하는것 같다
- inline 함수라면, runCatching 의 block 호출 코드가 그대로 부모 suspend 함수에 위치하게 되므로, 문제가 없어지는것 같다

**Comment by wjchoi96** [comment]
```
inline fun <T, R> T.runCatching(block: T.() -> R): DomainResult<R> {
    return try {
        DomainResult.Success(block())
    } catch (e: Throwable) {
        DomainResult.Failure(e)
    }
}
```
함수를 생성

해당 함수를 호출하는 부분은 아래와 같다

```
suspend operator fun invoke(): Flow<DomainResult<List<BanchanModel>>> {
    return banchanRepository.fetchMainDishBanchan()
        .map {
            val baseList = listOf(
                BanchanModel.empty().copy(viewType = BanchanModel.ViewType.Banner),
                BanchanModel.empty().copy(viewType = BanchanModel.ViewType.Header),
            )
            DomainResult.runCatchingWithData( // 위에서 생성한 함수 호출
                baseList
            ) {
                val cart = fetchCartItemsKeyUseCase().getOrThrow() // suspend function
                baseList + it.getOrThrow().map {
                    if(cart.contains(it.hash))
                        it.copy(isCartItem = true)
                    else
                        it
                }
            }
        }
}
```

이때, `fetchCartItemsKeyUseCase` 는 suspend 함수가 되는데,  `DomainResult.runCatchingWithData` 함수를 `inline` 함수로 설정하면 문제가없고, `inline` 함수로 설정하지 않으면 에러가 난다

**Comment by wjchoi96** [comment]
Inline 함수에 대해서는 공부를 했고, 추측되는 이유도 있지만, 정확한 이유를 알고 싶어서 직접 확인

**아래는 inline으로 설정하지 않았을때의 코드**
```
fun <T, R> T.runCatchingForDebug(block: T.() -> R): R? {
    return try {
        block()
    } catch (e: Throwable) {
        null
    }
}

fun main() {
    val result = 20.runCatchingForDebug{
        this + 10
    }
    println(result)
}
```
해당 코드가 아래의 Java 코드로 변환되는 것을 확인
```
public final class TestKt {
    // @NotNull Function1 block => 람다가 객체화 되었다
   @Nullable
   public static final Object runCatchingForDebug(Object $this$runCatchingForDebug, @NotNull Function1 block) {
      Intrinsics.checkNotNullParameter(block, "block");

      Object var2;
      try {
         var2 = block.invoke($this$runCatchingForDebug); // 객체화 된 람다 호출
      } catch (Throwable var4) {
         var2 = null;
      }

      return var2;
   }

   public static final void main() {
        // this + 10 코드가 (Function1)null.INSTANCE 처리 되어서 전달되는것으로 보인다
        Integer result = (Integer)runCatchingForDebug(20, (Function1)null.INSTANCE);
        System.out.println(result);
   }

   // $FF: synthetic method
   public static void main(String[] var0) {
      main();
   }
}

```

```
val result = 20.runCatchingForDebug{
        this + 10
}
```
의 `this+10` 코드가 `Function1)null.INSTANCE` 처리 되어서 전달되는것으로 보인다 
떄문에, block 내부에서 suspend 함수를 호출했을때, 에러가 나는것으로 보인다
마치 아래의 코드에서 에러가 발생하는것 처럼 말이다
```
private fun runAtScope(){
    viewModelScope.launch {
        callSuspendFun()
    }
}
private fun callSuspendFun(){
    suspendFunction() // error:: Suspend function 'invoke' should be called only from a coroutine or another suspend function
}
```

**Comment by wjchoi96** [comment]
**그렇다면 Inline 함수로 설정했을때는 어떻게 되는걸까?**
```
inline fun <T, R> T.runCatchingForDebug(block: T.() -> R): R? {
    return try {
        block()
    } catch (e: Throwable) {
        null
    }
}

fun main() {
    val result = 20.runCatchingForDebug{
        this + 10
    }
    println(result)
}
```

코드가 아래와 같이 변환된다
```
public final class TestKt {
   @Nullable
   public static final Object runCatchingForDebug(Object $this$runCatchingForDebug, @NotNull Function1 block) {
      int $i$f$runCatchingForDebug = 0;
      Intrinsics.checkNotNullParameter(block, "block");

      Object var3;
      try {
         var3 = block.invoke($this$runCatchingForDebug);
      } catch (Throwable var5) {
         var3 = null;
      }

      return var3;
   }

   public static final void main() {
      int $this$runCatchingForDebug$iv = 20;
      boolean var2 = false;

      Integer var3;
      try {
         int var4 = false;
         var3 = $this$runCatchingForDebug$iv + 10;
      } catch (Throwable var5) {
         var3 = null;
      }

      System.out.println(var3);
   }

   // $FF: synthetic method
   public static void main(String[] var0) {
      main();
   }
}
```

**Comment by wjchoi96** [comment]
- #112 
해당 `Issue`의 변경사항으로 인하여 더 좋은 형태로 발전되었다고 판단해, 해당 `Issue`, `PR`은 `close`처리
