### ISSUE TITLE
[Design] 공통 컴포넌트 개발

### ISSUE THREAD

**Issue by YM-Byun** [woowa-techcamp-2022/android-banchan-06#8]
## 📪 Issue
공통 컴포넌트 xml 디자인을 합니다
### 

## 📚 To-do
- [x] Colors 추가
- [x] Icons 추가
- [ ] View toggle button 구현
- [ ] Floating menu 구현
- [ ] Appbar design
- [x] Large button 구현
- [ ] Alert dialog 구현
- [x] Popup box 구현
- [x] Card 구현
- [ ] Tab navigation 구현

## 🕐 목표 작업 시간
08.09 22:00 - 08.10 00:30
